### PR TITLE
Move load file methods from Base to Simple Backend

### PR DESCRIPTION
**Pull request by davidgaya**
All the logic to load translations from files has to be in the Simple Backend (as this is its responsibility).

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
By looking at the code it seems to make sense, however I wonder if there aren't any other external dependencies depending on this API from Base, that could break as soon as we push a new version. Any thoughts?

**Comment by davidgaya** [comment]
If someone has her own Backend using this functionallity from Base, it will brake, no doubt.
Its a trade, to bloat Base with methods not used by other Backends, or to risk braking someones Backend.

I have the idea of refactoring Simple to split the two current responsibilities (hash store and file loading) in different modules. That way it will be easier to create/fix a Backend that only uses one of the features.

**Comment by radar** [comment]
Hey @davidgaya, could you please update this branch against the current master branch?

Thanks!

**Comment by davidgaya** [comment]
@radar I don't understand why the travis test failed at the bundle install step. Can you give me a hint ?

**Comment by radar** [comment]
@davidgaya Ensure that your branch is on the latest master.

**Pull request closed without merging**
