### PR TITLE
Replace custom module for refinements with Gorilla Patch gem

### PR DESCRIPTION
**Pull request by AlexWayfer**
I'm not sure that you'll like it, but I like to split code into dependencies instead of duplicating code in projects.

I've mentioned this change in https://github.com/ruby-i18n/i18n/pull/424#issuecomment-406851149.

### CODE REVIEW

**Comment by radar** [comment]
Thanks for the patch but I would rather keep the dependencies simple for this gem.

**Comment by AlexWayfer** [comment]
> Thanks for the patch but I would rather keep the dependencies simple for this gem.

Can you somehow to argument this point? It looks like "Thank you, I'll not use I18n (or Ruby on Rails), I'll write and maintain my own code instead".

**Comment by radar** [comment]
I got out of OSS originally because of such petty arguments. Can we not?

**Comment by AlexWayfer** [comment]
> I got out of OSS

When? I see pretty green GitHub table, but it can't be filtered only with OSS.

> originally because of such petty arguments.

Can I look at discussions? I can read your opinion without repeating.

> Can we not? 

Yes.

**Comment by radar** [comment]
The table is green on Monday to Friday mainly. Hmmm perhaps I use GitHub for work?

**Comment by AlexWayfer** [comment]
> Hmmm perhaps I use GitHub for work?

Probably, I didn't exclude this, but this is not an answer for any of two my questions. OK.

**Pull request closed without merging**
