### PR TITLE
Revert "Fix missing requires of i18n/core_ext/hash"

### PR DESCRIPTION
**Pull request by radar**
Reverts ruby-i18n/i18n#574

This was breaking the master build.

### CODE REVIEW

**Comment by dvzrv** [comment]
An update would be highly appreciated, as I can not build (and test) this when attempting to create the package on Arch Linux.

**Comment by dvzrv** [comment]
Out of general curiosity: How did this not make [all tests in CI](https://github.com/ruby-i18n/i18n/blob/master/.github/workflows/ruby.yml#L65) fail since August and more specifically when that commit was added via pull request in https://github.com/ruby-i18n/i18n/pull/574? :thinking:

**Comment by radar** [comment]
@dvzrv Please be aware that I am the sole maintainer and located in Australia. When you posted your comment, the local time was 6:27am.

@jordan-brough I can yank 1.9.0 so that it's uninstallable, after I release a 1.9.1.

**Comment by dvzrv** [comment]
> Please be aware that I am the sole maintainer and located in Australia. When you posted your comment, the local time was 6:27am. The PR you're pointing to was created in August, but was only merged ~22hrs ago.

Ah good point! Didn't notice that :)
I have applied it for the package on Arch Linux. Thanks for merging! :heart:

**Comment by kwisatz** [comment]
How is #574 supposed to be resolved in environments that exhibit this problem. E.g. in one of our `decidim` installations, we do see the same problem:

```
decidim@marklar:~/decidim$ bundle exec rails db:migrate --trace                                            
** Invoke db:migrate (first_time)                                                                                  
** Invoke db:load_config (first_time)                                                                              ** Invoke environment (first_time)
** Execute environment                                                                                             rails aborted!      
NameError: uninitialized constant I18n::HashRefinements                                                            /home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-term_customizer-0e823f4f768f/li
b/decidim/term_customizer/i18n_backend.rb:9:in `<class:I18nBackend>' 
[…]
```

**Comment by radar** [comment]
Refinements were removed here: https://github.com/ruby-i18n/i18n/pull/573

Either change your code to remove the reference to refinements, or use a version of i18n that still has them.

**Comment by radar** [comment]
I’m out and about now, just on my phone. I’ll need to double check this as #573 has other issues that are reported against it. Seems like I might be missing something here on my little screen.

**Pull request merged**
