### PR TITLE
Drop support of Ruby < 2.3 and Rails < 4.2

### PR DESCRIPTION
**Pull request by AlexWayfer**
https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

https://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/

### CODE REVIEW

**Comment by radar** [comment]
Thanks @AlexWayfer. I’ll look into merging this later this week as I have other PRs queued up for a 1.1 release. When changing the version restrictions like this I like to release them in a new 1.x release. So here’s what I’ll do:

* get to the 1.1 release at some point this week
* review your PR again and double check it
* merge the PR
* release 1.2 with only your change in it

Does that sound good to you?

**Comment by AlexWayfer** [comment]
Thanks, good.

But, please, consider, that my plans are also make a PR with moving from core-class Hash patching (what is dangerous) to refinements, especially via [`gorilla_patch` gem](https://github.com/AlexWayfer/gorilla_patch).

We can switch to refinements in 1.2 or 1.3, as I wish. I don't see any problems to make it in 1.2, after this PR.

**Comment by oniofchaos** [comment]
👍

**Comment by AlexWayfer** [comment]
> I think we'll have better reasons to merge this when Rails 6 rolls around

Yep: https://github.com/rails/rails/pull/32028

OK, I agree. Thanks for the research. I didn't think that Rails allows Ruby 2.2. And I think that this PR can be merged for version 2 (or 3), which will be for Rails 6.

**Comment by deivid-rodriguez** [comment]
@radar Just out of curiosity, did you try this? I would think `bundler` would be able to resolve this situation properly and install a previous version of `i18n` with a less strict `required_ruby_version` requirement on ruby 2.2. If that's not happening, I'd say that's a bug in bundler!

**Comment by AlexWayfer** [comment]
Conflicts resolved (I hope correct).

**Comment by radar** [comment]
@deivid-rodriguez No, I haven't tried it out. I was only guessing at what Bundler might do. Looking at the code within Bundler, I believe you are correct: it will handle `required_ruby_version` fine. 

I still do not feel comfortable releasing this until Rails 6 comes out. Nothing is requiring i18n to jump ahead like this just yet.

**Comment by deivid-rodriguez** [comment]
@radar Fair enough, I just wanted to make sure there wasn't a bug in bundler worth fixing! :+1:

**Comment by shushugah** [comment]
rails 6 is now out :)

**Comment by AlexWayfer** [comment]
Yes, but this PR is made (duplicated) in:
* https://github.com/ruby-i18n/i18n/commit/d8a2d5c55d73cd64351664a756024285867d555b
* https://github.com/ruby-i18n/i18n/commit/fb0c8beb29cf75fbb82b66339284e8e3f31ecaff
* https://github.com/ruby-i18n/i18n/commit/213641fe9a0c8f59c5b7d57b2e437d9cf4cfc825

**Pull request closed without merging**
