### PR TITLE
Performance changes

### PR DESCRIPTION
**Pull request by thedarkone**
I18n started showing up in perf profiles for my app again. I'm no longer that much familiar with the I18n's codebase as I used to be, so some code review is really welcome.

### CODE REVIEW

**Comment by radar** [comment]
@thedarkone / @tenderlove any interest in getting this PR across the line for i18n 0.8.0?

**Comment by thedarkone** [comment]
@radar what is the timetable? Would it be acceptable if I would need maybe up to 3-4 weeks time to look at it?

**Comment by radar** [comment]
@thedarkone I don't have any particular timetable in mind yet. The i18n gem hasn't received a version bump since Dec '14. It can wait a little while longer. If you need 3-4 weeks to complete it, then that's OK with me. :+1:

**Comment by radar** [comment]
Bumping this to 0.9.0. Looking to prep a 0.8.0 beta release for December, with a 0.9.0 next quarter.

**Pull request closed without merging**
