### PR TITLE
Always instantiate I18n::Locale::Fallbacks objects when using I18n.fallbacks=

### LINKED ISSUE #534: TypeError (no implicit conversion of String into Integer) -- While using `I18n.l`
I had: 

```rb
I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
I18n.enforce_available_locales = false
```

And things like: 

```rb
I18n.l product.updated_at, :format => :long, :locale => "un-supported"
```

Worked great! Used default locale's `:long`.

Then I upgraded to said version, and I cannot get this behavior back.

```rb
I18n::Backend::Simple.send :include, I18n::Backend::Fallbacks
I18n.enforce_available_locales = false
I18n.fallbacks = [I18n.default_locale]
```
Gives:

```rb
Traceback (most recent call last):
       14: from ./bin/rails:4:in `<main>'
       13: from ./bin/rails:4:in `require'
       12: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
       11: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
       10: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        9: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        8: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        7: from (irb):1
        6: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/i18n-1.1.0/lib/i18n.rb:274:in `localize'
        5: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/i18n-1.1.0/lib/i18n/backend/base.rb:83:in `localize'
        4: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/i18n-1.1.0/lib/i18n.rb:181:in `translate'
        3: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/i18n-1.1.0/lib/i18n.rb:181:in `catch'
        2: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/i18n-1.1.0/lib/i18n.rb:185:in `block in translate'
        1: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/i18n-1.1.0/lib/i18n/backend/fallbacks.rb:45:in `translate'
TypeError (no implicit conversion of String into Integer)
```

```rb
I18n.enforce_available_locales = false
I18n.fallbacks = [I18n.default_locale]
```

Along with other seemingly correct config permutations give:

```
I18n::MissingTranslationData (translation missing: XX.time.formats.long)
```

Back to 1.0.1! 🔒

_Originally posted by @sshaw in https://github.com/ruby-i18n/i18n/pull/415#issuecomment-649180548_

### PR DESCRIPTION
**Pull request by radar**
Should fix #534.

### CODE REVIEW

**Comment by radar** [comment]
@sshaw Would you mind trying out this branch within the next ~12ish hours? If it's fine for you and for CI, I'm happy to merge it and do a 1.8.4 release.

**Comment by sshaw** [comment]
Using the same config which, from your comments on #534 seems to be the goal, I get: 

```
rails [5.0.7.2] (xxx)$ I18n.l Time.now, :format => :long, :locale => "XX"
Traceback (most recent call last):
       12: from ./bin/rails:4:in `<main>'
       11: from ./bin/rails:4:in `require'
       10: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        9: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        8: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        7: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        6: from /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        5: from (irb):1
        4: from /Users/sshaw/.rvm/gems/ruby-2.5.2/bundler/gems/i18n-741845cfec07/lib/i18n.rb:301:in `localize'
        3: from /Users/sshaw/.rvm/gems/ruby-2.5.2/bundler/gems/i18n-741845cfec07/lib/i18n/backend/base.rb:84:in `localize'
        2: from /Users/sshaw/.rvm/gems/ruby-2.5.2/bundler/gems/i18n-741845cfec07/lib/i18n.rb:211:in `translate'
        1: from /Users/sshaw/.rvm/gems/ruby-2.5.2/bundler/gems/i18n-741845cfec07/lib/i18n.rb:373:in `handle_exception'
I18n::MissingTranslationData (translation missing: XX.time.formats.long)
```

Config:

```
require "i18n/backend/fallbacks"

I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
I18n.enforce_available_locales = false
```

**Comment by sshaw** [comment]
**But**... 

```
I18n::Backend::Simple.send :include, I18n::Backend::Fallbacks
I18n.enforce_available_locales = false
I18n.fallbacks = [I18n.default_locale]
```

Works 🎆


One thing I do notice is the first calls to `I18n.l` takes maybe 4 seconds to return. Using rails-i18n too.

**Comment by radar** [comment]
@sshaw That first call to `I18n.l` will probably be `I18n` loading in your translations: [ref](https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/simple.rb#L89).

**Comment by radar** [comment]
@sshaw Thanks for your patience on this one. I have just pushed 1.8.4 with the changes from this PR.

**Pull request merged**
