### PR TITLE
Ruby 3.4 `Hash#inspect` compatibility.

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Review by radar — APPROVED** [review]

**Comment by radar** [comment]
Thank you! Could you please exclude Rails 6.1 + ruby-head from the matrix?

**Comment by radar** [comment]
And this combo: https://github.com/ruby-i18n/i18n/actions/runs/12235161164/job/34125870227?pr=709

**Comment by voxik** [comment]
> Thank you! Could you please exclude Rails 6.1 + ruby-head from the matrix?

I have included this patch if you prefer:

~~~patch
diff --git a/gemfiles/Gemfile.rails-6.1.x b/gemfiles/Gemfile.rails-6.1.x
index 6f67f78..43481a6 100644
--- a/gemfiles/Gemfile.rails-6.1.x
+++ b/gemfiles/Gemfile.rails-6.1.x
@@ -8,6 +8,8 @@ gem 'test_declarative', '0.0.6'
 gem 'rake'
 gem 'minitest', '~> 5.14'
 gem 'racc'
+gem 'base64'
+gem 'mutex_m'
 
 platforms :mri do
   gem 'oj'
~~~

**Comment by voxik** [comment]
> And this combo: https://github.com/ruby-i18n/i18n/actions/runs/12235161164/job/34125870227?pr=709

I'll do that. But it seems the matrix is incomplete. Rails 7.2 / 8.0 should likely be added.

**Comment by radar** [comment]
Agree. Make it so :)

**Comment by voxik** [comment]
> Agree. Make it so :)

Done.

I have noticed that `I18nTest#test_uses_the_simple_backend_by_default` test might be [flaky](https://github.com/ruby-i18n/i18n/actions/runs/12278460778). But I'm not going to investigate that.

Also, I'd say that the JRuby might need review.

**Review by radar — APPROVED** [review]

**Comment by radar** [comment]
Thank you for your diligence.

**Pull request merged**
