### PR TITLE
Update rails master to main

### PR DESCRIPTION
**Pull request by bjfish**
To correspond to the recent update:
https://weblog.rubyonrails.org/2021/1/24/this-week-in-rails-defaults-to-main-branch-name-new-webpacker-guide-and-improved-strict-loading/
https://github.com/rails/rails/commit/077c66d5d6ef3a6f1cc54e4a431bfa5ea6831b97

### CODE REVIEW

**Comment by bjfish** [comment]
CC @headius I saw a transient JRuby error on a test run here: https://github.com/ruby-i18n/i18n/runs/1764828272?check_suite_focus=true

**Comment by radar** [comment]
Thank you!

**Comment by headius** [comment]
@bjfish Transient as in it went away? It does not look like an error that would be transient (I would expect unpaired `catch`+`throw` to always fail).

**Comment by bjfish** [comment]
@headius Yes, it went away on subsequent runs.

**Comment by headius** [comment]
@bjfish @radar This appears to be a bug in the i18n tests. The same failure occurs with CRuby given that test seed:

```
[] ~/projects/i18n $ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

[] ~/projects/i18n $ SEED=18149 BUNDLE_GEMFILE=gemfiles/Gemfile.rails-main bundle exec rake
/Users/headius/.rvm/rubies/ruby-2.6.5/bin/ruby -w -I"lib:lib:test" /Users/headius/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/api/all_features_test.rb" "test/api/cascade_test.rb" "test/api/chain_test.rb" "test/api/fallbacks_test.rb" "test/api/key_value_test.rb" "test/api/memoize_test.rb" "test/api/override_test.rb" "test/api/pluralization_test.rb" "test/api/simple_test.rb" "test/backend/cache_file_test.rb" "test/backend/cache_test.rb" "test/backend/cascade_test.rb" "test/backend/chain_test.rb" "test/backend/exceptions_test.rb" "test/backend/fallbacks_test.rb" "test/backend/interpolation_compiler_test.rb" "test/backend/key_value_test.rb" "test/backend/memoize_test.rb" "test/backend/metadata_test.rb" "test/backend/pluralization_fallback_test.rb" "test/backend/pluralization_scope_test.rb" "test/backend/pluralization_test.rb" "test/backend/simple_test.rb" "test/backend/transliterator_test.rb" "test/core_ext/hash_test.rb" "test/gettext/api_test.rb" "test/gettext/backend_test.rb" "test/i18n/exceptions_test.rb" "test/i18n/gettext_plural_keys_test.rb" "test/i18n/interpolate_test.rb" "test/i18n/load_path_test.rb" "test/i18n/middleware_test.rb" "test/i18n_test.rb" "test/locale/fallbacks_test.rb" "test/locale/tag/rfc4646_test.rb" "test/locale/tag/simple_test.rb" 
test_declarative is deprecated for Minitest::Unit::TestCase
test_declarative is deprecated for Minitest::Test
Run options: --seed 18149

# Running:

......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................#<Concurrent::Map:0x00007f9683921b18 entries=3 default_proc=#<Proc:0x00007f9683921910@/Users/headius/projects/i18n/lib/i18n.rb:36>>
...........................................................................................................................................................................................................................................

Finished in 0.669325s, 2475.6284 runs/s, 3938.2960 assertions/s.

  1) Error:
I18nTest#test_localize_given_nil_and_default_returns_default:
UncaughtThrowError: uncaught throw :exception
    /Users/headius/projects/i18n/lib/i18n/backend/chain.rb:88:in `throw'
    /Users/headius/projects/i18n/lib/i18n/backend/chain.rb:88:in `localize'
    /Users/headius/projects/i18n/lib/i18n.rb:301:in `localize'
    /Users/headius/projects/i18n/test/i18n_test.rb:318:in `block in <class:I18nTest>'

1657 runs, 2636 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" /Users/headius/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/api/all_features_test.rb" "test/api/cascade_test.rb" "test/api/chain_test.rb" "test/api/fallbacks_test.rb" "test/api/key_value_test.rb" "test/api/memoize_test.rb" "test/api/override_test.rb" "test/api/pluralization_test.rb" "test/api/simple_test.rb" "test/backend/cache_file_test.rb" "test/backend/cache_test.rb" "test/backend/cascade_test.rb" "test/backend/chain_test.rb" "test/backend/exceptions_test.rb" "test/backend/fallbacks_test.rb" "test/backend/interpolation_compiler_test.rb" "test/backend/key_value_test.rb" "test/backend/memoize_test.rb" "test/backend/metadata_test.rb" "test/backend/pluralization_fallback_test.rb" "test/backend/pluralization_scope_test.rb" "test/backend/pluralization_test.rb" "test/backend/simple_test.rb" "test/backend/transliterator_test.rb" "test/core_ext/hash_test.rb" "test/gettext/api_test.rb" "test/gettext/backend_test.rb" "test/i18n/exceptions_test.rb" "test/i18n/gettext_plural_keys_test.rb" "test/i18n/interpolate_test.rb" "test/i18n/load_path_test.rb" "test/i18n/middleware_test.rb" "test/i18n_test.rb" "test/locale/fallbacks_test.rb" "test/locale/tag/rfc4646_test.rb" "test/locale/tag/simple_test.rb" ]
/Users/headius/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/headius/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/Users/headius/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Pull request merged**
